[package]
name = "actix-web-test"
version = "0.1.0"
authors = ["steshima <steshima@sonix.asia>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.0"
actix-rt = "1.1.1"